name: Federal Incentives
highlighter: rouge
baseurl: "/reading-room"
exclude:
  - .bundle
  - .git
  - .gitignore
  - bin
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
markdown: kramdown
collections:
- events
